version: '3.8'

services:
  employee-api:
    build: .
    container_name: employee-search-api
    ports:
      - "8000:8000"
    volumes:
      - ./test.db:/app/test.db      # mounts your DB into the container
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
